# Generated by Django 4.0.4 on 2022-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateField(auto_created=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('is_adopt', models.BooleanField(default=False)),
            ],
        ),
    ]
