# Generated by Django 4.0.4 on 2022-05-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='datecreation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pets',
            name='is_adopt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
