# Generated by Django 4.0.4 on 2022-05-29 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_alter_pets_datecreation_alter_pets_is_adopt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pets',
            name='is_adopt',
            field=models.BooleanField(default=False),
        ),
    ]
