# Generated by Django 4.0.4 on 2022-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pets_user_alter_pets_is_adopt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='descr',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
