# Generated by Django 4.0.4 on 2022-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pets_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='descr',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
